[features]
seeds = false
skip-lint = false
[programs.localnet]
staking_program = "YDmDZLkm7q8L3cBNRuAYqL4XvLQ2FQPHgLE5MzJQwhb"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/sensei/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
